### ISSUE TITLE
support for async calls in conditions

### ISSUE THREAD

**Issue by babsonmatt** [vadimdemedes/cancan#25]
Right now can/authorize wont wait for async conditions to finish before returning.. something like this doesn't work:

```js
allow(User, 'edit', User, async (user, target) => {
  const u = await User.findById(user.id);
  return u.id === 3;
});
```

Thanks!

**Comment by vadimdemedes** [comment]
That is a great catch! The problem is, this would require `can()` to be async too, unfortunately. I like the simplicity of synchronous `can()`:

```js
if (can(user, 'edit', post)) {
  // do smth
}
```

Considering your code example, `target` (user) should be pre-fetched. While I realize it may be useful, you shouldn't load anything in the validator function. It should only check source/target objects and validate the action.
